[package]
name = "rust_base"
version = "0.1.0"
authors = ["logan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
